### ISSUE TITLE
README.md exmaple warning

### ISSUE THREAD

**Issue by changsijay** [marvinpinto/ansible-role-docker#4]
warning message:
`found a duplicate dict key (tasks).  Using last defined value only.`

the first task `ensure that we can connect to this host` will not be executed.

**Comment by marvinpinto** [comment]
Ahh, neat! Found it in the [travis build](https://travis-ci.org/marvinpinto/ansible-role-docker#L161-L163) output as well:

``` text
 [WARNING]: While constructing a mapping from /home/travis/build/marvinpinto
/ansible-role-docker/tests/role.yml, line 2, column 3, found a duplicate dict
key (tasks).  Using last defined value only.
```

I think it should be safe to get rid of this task in the example as well as the tests:

``` yaml
  tasks:
    - name: 'Ensure that we can connect to this host'
      ping:
```

What are your thoughts @changsijay?
